### ISSUE TITLE
Security Recommendation: SPAs should use oidc Implicit Flow and not cookies

### ISSUE THREAD

**Issue by damienbod** [Azure-Samples/angular-cosmosdb#10]
OpenID http://openid.net/

Angular client https://github.com/damienbod/angular-auth-oidc-client

Node server https://github.com/panva/node-oidc-provider

or you can use Azure AD, provides oidc support

passportjs.org provides oidc support, but it is not certified.

http://passportjs.org/docs/openid

Also I would recommend only certified libraries. 
http://openid.net/certification/

**Comment by johnpapa** [comment]
+ @clarkio for comments

**Comment by clarkio** [comment]
@damienbod thank you for raising this issue. Could you elaborate on why this should not be using cookies?

**Comment by clarkio** [comment]
@damienbod please let us know your response by next week.

**Comment by damienbod** [comment]
@clarkio sorry, this got lost, didn't see your first answer. Cookies are harder to secure in SPA applications and OIDC Implicit Flow is the recommended best practice to secure SPA applications. The anti foregy protection helps with the cookies as do the extra HTTPS headers but if I can find a way to get the user to send my request,  my request will be sent with the other Identity. No way is perfect, but it just about finding the easiest way to reduce the attack area.

I think the OIDC specs are great and the people, organisations who made these have done massive work to help protect, authorize and authenticate the identities. I view the OIDC flows as the best practice for Web security at the moment. Then we are following a specification which is regularly reviewed, updated.

But then as always, a solution which works is a good solution. Junt my 3 cents.

Greetings Damien

**Comment by johnpapa** [comment]
@clarkio curious what you think here

**Comment by clarkio** [comment]
@damienbod thanks for getting back to us. I agree with your suggestion on the use of OIDC but I'm still not fully understanding your suggestion to not use cookies. I feel they are more secure as a means to transmit the token/auth data than through a standalone header but I'm open to hearing your thoughts on it further. Could you elaborate on this particular suggestion?

Here are some of my thoughts on the use of cookies for some context: 

If we don't use cookies to store the auth data then we're left to use session storage and then manually transmit this data as a header in any API requests. With a cookie, the browser will handle this transmission for us.

That said, the two common client-side attacks that cookies and tokens are potentially at risk of are cross-site request forgery and cross-site scripting. I feel XSS is the more difficult one to defend against because as an application gets larger and larger the risk increases. There are more areas that would need to be protected which can potentially be forgotten. If there is an available vector for such an attack then the auth data is susceptible to being compromised whether storing the data in session storage or a cookie. But with a cookie, we have the ability to limit the effect of the attack by flagging the cookie as "HTTPOnly" - with session storage there are no mechanisms available to us to accomplish this (that I'm aware of at least).

To be fair, by relying on a cookie-based transmission that user auth data could be at risk to CSRF but I believe it has a more limited surface area and is, therefore, easier to protect against. Protecting against this is needed in one approach that is applied across the application (something like the synchronizer token pattern or flagging the cookies as "SameSite")

**Comment by damienbod** [comment]
@clarkio Thanks for your answer. So, we are comparing cookies to tokens 😊I see the risks of XSS equal for both. I don’t see any difference when sending the tokens or cookies in a request. The CSRF is a cookie thing, is much harder for tokens, the hacker needs to understand the application and reverse engineer the localstorage or sessionstorage for the tokens. The HTTPonly only means I can’t use the cookie directly from javascript, but I could rebuild my attack logic like the application. Cookies are not ideal for APIs on the server, tokens have no session.

But the main question seems to be which is worse, saving your tokens to local storage/session storage, or CRSF attacks due to the fact that the browser automatically sends the cookie with each request. I believe it is better not the automatically send the auth data with each request, so if I want to attack this, I need to rebuild this, and as you said this is possible, if I study the storage of an active client. But this is also possible for HTTPonly cookies.

When I use MVC clients, (sever side rendering) I prefer to use tokens saved in the secure cookie and HTTP only, but not for SPA applications. 

Greetings Damien

**Comment by clarkio** [comment]
@damienbod I can see how my response would come off that way. My point is in comparing storage of the token either in a cookie or session/local storage. Cookie storage is a more hardened approach from a security perspective than session/local storage. You are correct there isn't a difference in sending the token in a cookie or as a standalone header. The difference is in the accessibility of the token through the storage mechanism. 

XSS attacks can have access to both storage mechanisms however a cookie has more security constraints available to it than session/local storage (such as "Secure" and "HTTPOnly"). So that along with the level of difficulty to catch and defend against all vectors of XSS lead me to believe that Cookie storage is the best approach. In other words, XSS is worse to defend against than CSRF. Does that help explain my perspective better?

The automatic sending of the cookie (the issue allowing CSRF) is becoming less of a problem with the new ["SameSite"  cookie flag](https://caniuse.com/#feat=same-site-cookie-attribute) along with other protections such as the [Synchronizer Token Pattern](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Synchronizer_.28CSRF.29_Tokens), [Double Submit Cookies](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Double_Submit_Cookie), etc.

Also, this is within the context of connecting with your own API and not a third-party API as we see in this example application. I can definitely see how sending the token via a standalone HTTP header is an appealing approach when working with third-party APIs but that is out of context for this example.

I hope this better explains my point of view. I do appreciate your input and am enjoying having this discussion with you. Please let's continue it and let me know your thoughts. However, we will close this issue by taking into consideration your suggestion in using OIDC but will continue with the use of a cookie as the storage mechanism and transmission vehicle for this example. Sound good?
